name: mirai

packages:
  - packages/*
  - examples/*

scripts:
  analyze:
    exec: dart analyze .
  format:
    exec: dart format .
  get:
    exec: flutter pub get
  build:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      ignore: mirai_framework
  watch:
    exec: dart run build_runner watch --delete-conflicting-outputs
    packageFilters:
      ignore: mirai_framework