name: mirai_web3_signer
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  mirai_framework: ^0.0.1
  # web3modal_flutter: ^3.1.0
  web3modal_flutter:
    git:
      url: https://github.com/WalletConnect/Web3ModalFlutter.git
      ref: master
  url_launcher:
  http: ^1.2.0
  web3dart: ^2.7.2
  # flutter_web3: ^2.1.9
  # web3dart: ^2.7.1
  # walletconnect_dart: ^0.0.11
  # url_launcher: ^6.2.4
  # walletconnect_flutter_v2:
  # web3modal_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
