name: Pull Request Checks
on:
  push:
    paths-ignore:
      - 'bricks/**'
  pull_request:
    paths-ignore:
      - 'bricks/**'

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Download all Flutter packages
      - name: Download dependencies
        run: flutter pub get

      # Run Flutter Format to ensure formatting is valid
      - name: Run Flutter Format
        run: dart format --set-exit-if-changed .

      # Run Flutter Analyzer
      - name: Run Flutter Analyzer
        run: flutter analyze

